### PR TITLE
Sampling for statsd monitor

### PR DESCRIPTION
**Pull request by alenkacz**

### CODE REVIEW

**Comment by alenkacz** [comment]
can I keep both variants? specify it on monitor level and override it on metric level if it makes sense?

when we had problems with statsd, it was typically just few metrics that were creating problems so not all metrics had to be sampled so that is the use case I wanted to cover

**Comment by augi** [comment]
Yep, keeping both variants sounds great!

**Comment by jendakol** [comment]
It's absolutely necessary to have the sampling rate specified on monitor level, since you always use just `Monitor` in your classes. But no problem with keeping both version (ability to override), however it will be very hardly usable...

**Comment by mixalturek** [comment]
Sampling rate on monitor level is nice from API level point of view but out of typical use cases. In 99.99% percent you want to set sampling only for few counters like incoming requests and have full rate for counters like errors that occur rarely. There may be very unwanted data loss that may affect alerting and health of your application. If the counter is defined inside an library it may be impossible to set proper sampling at all (e.g. in one application you want 100% and in another one only 1% for a concrete metric).

I would prefer an external configuration similar to "metrics filter" module (https://github.com/avast/metrics/pull/18). There is `enable = true/false` per tree of metrics at the moment. What about to add another field `sample = <0.0, 1.0>`? But it may be too statsd monitor specific.

**Comment by jendakol** [comment]
Closing this since it's been implemented in #22 in a better way.

**Pull request closed without merging**
